name: iskra
channels:
  - nvidia
  - conda-forge
dependencies:
  - python==3.12
  - conda-forge::ffmpeg
  - conda-forge::libxcrypt # nanobind fails to compile without this
  - pip
  - pip:
      # Core libraries
      - torch==2.12
      - nvmath-python[cu13-dx]
      - cuda-toolkit[nvcc,nvrtc]==13.0.*
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - numpy
      - scipy
      - networkx
      - cholespy
      # Mesh IO
      - trimesh
      - meshio
      - libigl
      - fsspec[http]
      - requests
      # Helpers
      - rich
      - typing-extensions
