name: iskra
channels:
  - conda-forge
dependencies:
  - ninja
  - pip
  - pip:
      # Linters:
      - ruff
      - flake8
      - flake8-copyright
      - mypy
      - black
      - isort
      - types-requests
      - nvtx
      # Visualization
      - matplotlib
      - jupyterlab
      - ipywidgets
      - widgetsnbextension
      - ipympl
      # Testing:
      - pytest
      - pytest-cases
      - pytest-cov
      # Documentation
      - mkdocs
      - mkdocs-material
      - mkdocstrings
      - mkdocstrings-python
      - mkdocs-autorefs
      - griffe_typingdoc
      # Deployment
      - nanobind>=2.5.0
      - scikit-build-core>=0.10.7
      - pyproject-metadata
      - setuptools
      - twine>=1.11.0
      - wheel
      - packaging
