name: iskra
channels:
  - conda-forge
dependencies:
  - ninja
  - pip
  - pip:
      # Linters:
      - ruff
      - nvtx
      # Visualization
      - matplotlib
      - jupyterlab
      - ipywidgets
      - widgetsnbextension
      - ipympl
      # Testing:
      - pytest
      - pytest-cases
      - pytest-cov
      # Documentation
      - mkdocs==1.6.1
      - mkdocs-material==9.6
      - mkdocstrings==0.28
      - mkdocstrings-python
      - mkdocs-autorefs==1.4.3
      # - mkdocs==1.6.1
      # - mkdocs-materialx==10.1.8
      # - mkdocstrings
      # - mkdocstrings-python
      - griffe_typingdoc
      # Deployment
      - nanobind>=2.5.0
      - scikit-build-core>=0.10.7
      - pyproject-metadata
      - setuptools
      - twine>=1.11.0
      - wheel
      - packaging
