name: mkdocs
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: dev
          environment-file: environment-dev.yaml
          auto-activate-base: false

      - name: Verify Conda Environment
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Build Site
        shell: bash -l {0}
        run: mkdocs build

      - name: Deploy to GitHub Pages
        shell: bash -l {0}
        run: mkdocs gh-deploy --force