name: Unit Tests

on:
  push:
  workflow_dispatch:
  pull_request:
    

jobs:
  test:
    name: Run Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment-dev.yaml
          activate-environment: test_env      

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate test_env
          pytest tests/
